# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'DailyDhanFull' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'DailyDhanFullTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
    
    # Fix for DateTimePicker C++ compilation issues with RN 0.76
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        # Set C++ standard for all targets
        config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++20'
        config.build_settings['CLANG_CXX_LIBRARY'] = 'libc++'
        
        # Specific fix for RNDateTimePicker override issues
        if target.name == 'RNDateTimePicker' || target.name.include?('RNDateTimePicker') || target.name.include?('RNDateTimePickerCGen')
          # Suppress the override warning that causes compilation errors
          config.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = 'YES'
          config.build_settings['CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER'] = 'NO'
          config.build_settings['CLANG_WARN_UNGUARDED_AVAILABILITY'] = 'NO'
          config.build_settings['WARNING_CFLAGS'] = '$(inherited) -Wno-error -Wno-inconsistent-missing-override'
          config.build_settings['OTHER_CPLUSPLUSFLAGS'] = '$(inherited) -Wno-inconsistent-missing-override'
        end
      end
    end
  end
end
